name: PyInstaller packaging example

on: workflow_dispatch

jobs:
  build:

    # runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Wxwidgets setup
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install python-wxgtk3.0 python-wxgtk3.0-dev
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: 'main.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'hello-world'
